# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linphone_sip_acct', models.CharField(max_length=200)),
                ('linphone_sip_pwd', models.CharField(max_length=200)),
            ],
        ),
    ]
