# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='speech_source',
            field=models.CharField(default=-1, max_length=2),
            preserve_default=False,
        ),
    ]
