# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_usersettings_speech_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='speech_source',
            field=models.IntegerField(),
        ),
    ]
