# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20171230_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='filename',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audiofiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
