# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-31 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20171231_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='~/Documents/typiremote/audiofiles/'),
        ),
    ]
